"""DISABLED — this script generated charts from invented data.

Phase 0 verification found that none of the plotted values came from
measurement. Every number was a hardcoded literal or synthesised:

  * ``times = [40, 250, 2500]``        - hardcoded "ms per move". The engine was
                                         measured at 617 ms mean, not 40 ms.
  * "6.2x faster" / "62x faster"       - hardcoded annotations. The engine was
                                         measured ~121x SLOWER than Stockfish
                                         at depth 8 on identical positions.
  * ``values = [0.506, 0.55, 180]``    - hardcoded correlation, "top move
                                         agreement" and "MAE". Measured top-1
                                         agreement is 0.1923; no MAE is computed
                                         anywhere in this project.
  * ``sizes = [11.2, 50]``             - hardcoded model sizes. The real files
                                         are 27.1 MB and 76.1 MB.
  * training curves                    - generated by
                                         ``25000*np.exp(-epochs/15)+15000+noise``
                                         and a matching synthetic correlation
                                         curve, while genuine per-epoch history
                                         exists in chess_model_FINAL.ipynb cell 15.

The four PNGs it produced were displayed in the web UI and have been removed.
The unmodified original is preserved at
``archive/phase1_invalid_benchmarks/generate_visualizations.py.original``,
together with the images it generated.

Verified figures: ``baseline/BASELINE.md``. Re-plotting real training history
from the notebook is possible future work; it is not done here because Phase 1
is an integrity pass, not a visualisation pass. Running this file exits non-zero.
"""
import sys

ARCHIVED_ORIGINAL = "archive/phase1_invalid_benchmarks/generate_visualizations.py.original"


def main() -> int:
    sys.stderr.write(
        "\n"
        "generate_visualizations.py is DISABLED.\n"
        "\n"
        "Every value it plotted was hardcoded or synthetic, including the\n"
        "'training curves'. The charts it produced have been removed from the UI.\n"
        "\n"
        "  Verified results: baseline/BASELINE.md\n"
        f"  Original script:  {ARCHIVED_ORIGINAL}\n"
        "\n"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
